import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase credentials");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const slugs = [
"GENESISS325SGASGRILLLIQUIDPRVE30WR",
"BOSCHCM10GD10DUALBEVELGLIDEMP3ISF6",
"EDRIFTFATBEARFATSCOUTELECTRIQCACFC",
"ESCO3TONPERFORMANCEAXLETOPPO7DONW4",
"DK24FTX25FTUTILITYTRAILER1104RVSGN",
"GP9FPACKAGE51752549000LBCAPA7N53ZM",
"BRIGGSAMPSTRATTON115TPSNOWENLN78RA",
"DELONGHINESPRESSOVERTUOPLUSDZY6V09",
"CHALLENGERLIFTS90TRANSMISSIOQJF98D",
"ESCOYAK3366TONAIRHYDRAULICJA7Q1Y82",
"BACKYARDDISCOVERY14FTX10FTSTMGNMRX",
"BREVILLETHEBAMBINOPLUSESPRES7K8UJH",
"DOLPHINPROTEUSDX5IWIFIROBOTILPUHV5",
"HIBOYS2PROELECTRICSCOOTER500JGLQC8",
"HUSQVARNAAUTOMOWER115HROBOTI2EX3LN",
"HUSQVARNA125B28CC2CYCLEHANDH3VHRO3",
"BACKYARDDISCOVERYSKYFORTIISW1WNTMS",
"DK25FTX7FTSTEELUTILITYTRAILEPVTDTN",
"BRIGGSAMPSTRATTON13D13600102PKSDD1",
"DEWALT21163CCSELFPROPELLEDLABZE6EX",
"CRAFTSMANV20LAWNMOWERPUSHMOWCANP1Y",
"EGOSNT2400SNOWBLOWER7GBNUK",
"BACKYARDDISCOVERYSPRINGCOTTAHBL1K0",
"CUBCADET2X30357CCTWOSTAGESNO03SAGL",
"HAMPTONTRADITIONALSTEELCABANUNASFP",
"GRAVELYZTHD52ZEROTURNMOWERKAL9ZARF",
"HUSQVARNA48SNOWAMPDOZERBLADE3NHFEN",
"GREENWORKS40V20CORDLESSMOWERQ6SUA5",
"BIGTEXHEAVYDUTYTANDEMAXLEPIP3E48MI",
"BADBOYROGUE61COMMERCIALZEROT2SEA1W",
"HILLCRESTSWINGSETCL2V0O",
"HUSQVARNA58255980148INCLEARC07DB4L",
"CUBCADETCC60028224CCWALKBEHIPUNH5F",
"CUBCADETJS1150JETSWEEPWALKBEJ5KRNW",
"DENONDP450USBHIFITURNTABLEWI6PR2T2",
"CUBCADET2X26INTELLIPOWERTWOS8SQATN",
"BIGTEXPROSERIESTANDEMAXLESINHIM381",
"COLDPLUNGEPROCOLDWATERIMMERSWCTAXA",
"CUBCADETDOUBLEBAGGERFORXT1ANP88CZV",
"BACKYARDDISCOVERYSTEELTRADIT4H9QMN",
"BRIGGSAMPSTRATTONHORIZONTALSWV2SPY",
"HUSQVARNAL421P21173CCKOHLERP707EE7",
"DELONGHIDINAMICATRUEBREWOVER132BC4",
"DUROMAXXP13000HXT13000WATTELKKN047",
"EPROPULSIONELITE15HP500WELECHN2R2H",
"CAT60V21INBRUSHLESSLAWNMOWERXC6A85",
"BACKYARDDISCOVERYMCKINLEYMOUEWFZ5B",
"DELONGHILASPECIALISTAESPRESSVD9CD2",
"CHAMPIONPOWEREQUIPMENT2009058JA4WS",
"DOLPHINPROTEUSDX5IWIFIROBOTIRPQZ3W",
"HUSQVARNA970458901Z248FZTURN7D9D48",
"CUBCADET3X26TRACTHREESTAGESN38KY8R",
"FRIGIDAIREGALLERY24DISHWASHEAUMT49",
"FACTOR6X6FTSTRONGSTORAGESHED6BBKB0",
"DUROMAX13000WATTTRIFUELPORTA1HI7QO",
"COLEMANPOWERSPORTSGK100ONESEHEZLVZ",
"BIGTEXHEAVYDUTYIBEAMEQUIPMEN4QTIWJ",
"DELONGHIESPRESSOMACHINEWITH1QBH4FI",
"ATCOGT38HTWINRIDEONMOWERER8O27",
"GREENWORKS60V42CORDLESSBATTELHW3UN",
"DISCOVERYMOTORCYCLETRAILERQS3VZ1",
"EGO2175AH56VBATTERYPOWEREDSEQS420P",
"HONDA21INSTEELDECKELECTRICSTN6X5KK",
"DANIKA5PERSON68JETHOTTUBWITHHP4SSM",
"DK2POWERGASPOWEREDAMPCOMMERCQXWQA9",
"ESCO32TONAIRBAGJACKKIT32ZZUQ",
"DOLPHINSIGMAROBOTICPOOLCLEANGTFAEC",
"BESTBARNS12FTX20FTARLINGTONWROXRFR",
"DYSONV11TORQUEDRIVECORDLESSVGK5728",
"HAWTHORNETRADITIONALSTEELPERBE961G",
"DEWALTDXPW3000EELECTRICPRESS1JDUEN",
"HUSQVARNA970514302130C28CCCULUNMZ7",
"CUBCADETSC300SELFPROPELLEDLAHHP4LF",
"GOSERIESSINGLERAILFOLDINGMOT5UYTJW",
"COMMERCIALHEATEDCARPETAMPUPHELKOT6",
"CEDARFARMHOUSEPORCHSWINGLIGHLLTFJE",
"HEARTLANDCORONADO12X8GABLEENQKSOWO",
"DURAMATE8FTWX6FTDPLASTICSTORMK0CWP",
"ELEGANTCEDARWOODPERGOLAPERFEPBF65J",
"HEINWERNER20TONAIRACTUATEDTRPUDK70",
"DYSONV15DETECTVACUUMONECOLORNGND8H",
"ATLAS14000LBSCOMMERCIAL4POSTQ4QQXX",
"BRIGGSAMPSTRATTON20679190CCGWMTSSF",
"BADBOYMOWERSMZRAMBLER42IN19H78LFJV",
"BRIGGSAMPSTRATTONGENERATOR80Z1N1EA",
];

async function updateProducts() {
  console.log(`Starting update for ${slugs.length} products...`);
  
  for (let slug of slugs) {
    slug = slug.toLowerCase();
    
    const { data: product, error: fetchError } = await supabase
      .from('products')
      .select('meta')
      .eq('slug', slug)
      .single();
      
    if (fetchError || !product) {
      console.error(`Failed to fetch ${slug}:`, fetchError?.message || "Not found");
      continue;
    }
    
    const newMeta = { ...(product.meta || {}), gmc_enabled: false };
    
    const { error: updateError } = await supabase
      .from('products')
      .update({ meta: newMeta })
      .eq('slug', slug);
      
    if (updateError) {
      console.error(`Failed to update ${slug}:`, updateError.message);
    } else {
      console.log(`Successfully disabled GMC for ${slug}`);
    }
  }
  
  console.log('Finished updating GMC products.');
}

updateProducts();
